### ISSUE TITLE
Memory Corruption Issue

### ISSUE THREAD

**Issue by guyinatuxedo** [pepperke/dns_server#2]
Hey, just letting you know, the `read_qname` function has an issue when it increments `msg_ptr` without checking if it will push the ptr past the bounds of the char buffer. Thank you, and have a nice day!

**Comment by pepperke** [comment]
Hi, guyinatuxedo!
Thank you for code inspection. Right now I'm not really interested in further development of the project, as it fulfilled its original goal ;) But if I ever come back to it I will surely fix this (and most certainly not only this).
